#!/usr/bin/env python3
"""ckpt2preamble.py -- turn an interp_mips checkpoint (saveState.cc format) into
material that resumes the SAME architectural state on SILICON (the r9999/henry core),
where there is no DPI to seed regs/CP0/TLB.

Emits two files:
  <out>.S     -- a MIPS preamble (runs at the reset vector 0xbfc00000).  It installs
                 the 48 TLB entries, the CP0 state, FPRs, and GPRs, then ERETs to the
                 checkpoint PC.  Assemble with the mips64 toolchain, objcopy -O binary,
                 and stage it where henry_arcs.bin lives (@0xBFC00000).
  <out>.cimg  -- the checkpoint's memory pages as [u32 num][ (u32 pa, 4096B) x num ];
                 the ARM PS writes each page to DRAM[fpga_map(pa)] before releasing reset.

Layout of cp_header (must match interp_mips/saveState.cc, packed):
  u64 magic; i64 pc; i64 gpr[32]; i64 hi; i64 lo;
  u32 cpr0[32]; u64 cpr0_64[32]; u64 cpr1[32]; u32 fcr1[5];
  {u64 entry_hi,entry_lo0,entry_lo1; u32 page_mask,_pad;} tlb[48];
  u64 icnt; u32 num_pages;
then num_pages * { u32 va; u8 data[4096]; }
"""
import struct, sys

MAGIC = 0x6d697073f5f5d005

# CP0 register numbers
INDEX,RANDOM,ENTRYLO0,ENTRYLO1,CONTEXT,PAGEMASK,WIRED = 0,1,2,3,4,5,6
BADVADDR,COUNT,ENTRYHI,COMPARE,STATUS,CAUSE,EPC,XCONTEXT = 8,9,10,11,12,13,14,20
SR_EXL = 1 << 1

def parse(fn):
    b = open(fn,'rb').read()
    o = 0
    magic, pc = struct.unpack_from('<qq', b, o); o += 16
    assert (magic & (2**64-1)) == MAGIC, "bad magic"
    pc &= (2**64-1)
    # The checkpoint stores kseg pcs ZERO-extended (interp's 32-bit va2pa); the CPU
    # decodes the full 64-bit VA on ERET, where that is xuseg (mapped) -> derails.
    # Sign-extend a compat-32 pc from bit31; leave a true n64 pc (high32!=0) alone.
    if (pc >> 32) == 0 and (pc & 0x80000000):
        pc |= 0xffffffff00000000
    gpr = list(struct.unpack_from('<32q', b, o)); o += 256
    hi, lo = struct.unpack_from('<qq', b, o); o += 16
    cpr0 = list(struct.unpack_from('<32I', b, o)); o += 128
    cpr0_64 = list(struct.unpack_from('<32Q', b, o)); o += 256
    cpr1 = list(struct.unpack_from('<32Q', b, o)); o += 256
    fcr1 = list(struct.unpack_from('<5I', b, o)); o += 20
    tlb = []
    for _ in range(48):
        ehi, elo0, elo1 = struct.unpack_from('<3Q', b, o); o += 24
        pm, _pad = struct.unpack_from('<2I', b, o); o += 8
        tlb.append((ehi, elo0, elo1, pm))
    icnt, npages = struct.unpack_from('<QI', b, o); o += 12
    pages = []
    for _ in range(npages):
        va, = struct.unpack_from('<I', b, o); o += 4
        pages.append((va & 0xffffffff, b[o:o+4096])); o += 4096
    return dict(pc=pc, gpr=gpr, hi=hi, lo=lo, cpr0=cpr0, cpr0_64=cpr0_64,
               cpr1=cpr1, fcr1=fcr1, tlb=tlb, icnt=icnt, pages=pages)

def dli(reg, val):
    """Self-contained 64-bit load into $reg (no scratch, no $at)."""
    return "\tdli\t$%s, 0x%016x" % (reg, val & (2**64-1))

def emit_S(c, out):
    L = []
    a = L.append
    a("/* auto-generated by ckpt2preamble.py -- resume checkpoint icnt=%d pc=0x%08x */"
      % (c['icnt'], c['pc'] & 0xffffffff))
    a("\t.set\tnoreorder")
    a("\t.set\tnoat")
    a("\t.set\tmips64")
    a("\t.text")
    a("\t.globl\t_start")
    a("_start:")
    a("\t/* mask interrupts while we set up (EXL=1, and stay in kernel) */")
    a("\tmfc0\t$k0, $%d" % STATUS)
    a("\tori\t$k0, $k0, 0x%x" % SR_EXL)
    a("\tmtc0\t$k0, $%d" % STATUS)
    a("")
    a("\t/* ---- install the 48 TLB entries ---- */")
    for i, (ehi, elo0, elo1, pm) in enumerate(c['tlb']):
        a(dli('k0', ehi));  a("\tdmtc0\t$k0, $%d" % ENTRYHI)
        a(dli('k0', elo0)); a("\tdmtc0\t$k0, $%d" % ENTRYLO0)
        a(dli('k0', elo1)); a("\tdmtc0\t$k0, $%d" % ENTRYLO1)
        a(dli('k0', pm));   a("\tmtc0\t$k0, $%d"  % PAGEMASK)
        a("\tli\t$k0, %d" % i); a("\tmtc0\t$k0, $%d" % INDEX)
        a("\ttlbwi")
    a("")
    a("\t/* ---- CP0 (skip read-only PRId/Config/Random; skip BadVAddr) ---- */")
    for name, rno, is64 in [("Wired",WIRED,False),("Count",COUNT,False),
                            ("Compare",COMPARE,False),("EntryHi",ENTRYHI,True),
                            ("Context",CONTEXT,True),("XContext",XCONTEXT,True),
                            ("Cause",CAUSE,False)]:
        val = c['cpr0_64'][rno] if is64 else c['cpr0'][rno]
        a("\t/* %s */" % name)
        a(dli('k0', val))
        a("\t%s\t$k0, $%d" % ("dmtc0" if is64 else "mtc0", rno))
    a("")
    a("\t/* ---- HI/LO ---- */")
    a(dli('k0', c['hi'] & (2**64-1))); a("\tmthi\t$k0")
    a(dli('k0', c['lo'] & (2**64-1))); a("\tmtlo\t$k0")
    a("")
    a("\t/* ---- FPRs (FR=1, 64-bit each) + FCR31 ---- */")
    a("\t/* ensure CU1 so the mtc1s take */")
    a("\tmfc0\t$k0, $%d" % STATUS)
    a("\tlui\t$k1, 0x2000")     # CU1 = bit 29
    a("\tor\t$k0, $k0, $k1")
    a("\tmtc0\t$k0, $%d" % STATUS)
    for i in range(32):
        a(dli('k0', c['cpr1'][i]))
        a("\tdmtc1\t$k0, $f%d" % i)
    a(dli('k0', c['fcr1'][4]))   # FCR31
    a("\tctc1\t$k0, $31")
    a("")
    a("\t/* ---- restore GPRs (self-contained; k0/k1 done last as scratch) ---- */")
    for r in range(1, 32):
        if r in (26, 27):   # k0,k1 restored below
            continue
        a(dli(str(r), c['gpr'][r] & (2**64-1)))
    a("")
    a("\t/* ---- land at the checkpoint PC via ERET ---- */")
    a(dli('k0', c['pc'] & (2**64-1)))
    a("\tdmtc0\t$k0, $%d" % EPC)
    a("\t/* final Status: checkpoint value, forced EXL so ERET returns cleanly */")
    a(dli('k0', (c['cpr0'][STATUS] | SR_EXL) & 0xffffffff))
    a("\tmtc0\t$k0, $%d" % STATUS)
    a(dli('27', c['gpr'][27] & (2**64-1)))   # restore k1
    a(dli('26', c['gpr'][26] & (2**64-1)))   # restore k0 (last scratch use)
    a("\teret")
    a("\tnop")
    open(out + ".S", "w").write("\n".join(L) + "\n")

def emit_cimg(c, out):
    with open(out + ".cimg", "wb") as f:
        f.write(struct.pack("<Q", c['icnt']))        # base icnt (for --verify offset)
        f.write(struct.pack("<I", len(c['pages'])))
        for va, data in c['pages']:
            f.write(struct.pack("<I", va)); f.write(data)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: ckpt2preamble.py <checkpoint.bin> <out-prefix>")
    c = parse(sys.argv[1])
    emit_S(c, sys.argv[2])
    emit_cimg(c, sys.argv[2])
    print("wrote %s.S (%d TLB, 32 FPR, 31 GPR) and %s.cimg (%d pages), resume pc=0x%08x icnt=%d"
          % (sys.argv[2], 48, sys.argv[2], len(c['pages']), c['pc'] & 0xffffffff, c['icnt']))
