#!/usr/bin/env python3
"""Emit a MIPS 'loader shim' that restores an interp_mips checkpoint.

WHY a shim rather than DPI back-door loaders:
  * one mechanism instead of two -- no loadgpr/loadfpr/loadcp0/loadtlb imports to
    keep in step with the ISA's own semantics;
  * runs in ooo_core, henry_tb AND on the FPGA -- DPI is simulation-only, so a
    checkpoint becomes a portable artifact rather than a simulator feature;
  * cannot express unreachable state -- everything it sets, it sets with real
    instructions, so no illegal Status/TLB/ASID combinations that fabricate bugs;
  * restores only ARCHITECTURAL state, leaving caches cold, so one checkpoint is
    valid across every cache/ROB/scheduler geometry -- which is what makes a
    parallel config sweep possible at all.

Memory is NOT restored here: the checkpoint's pages are loaded by the normal
image loader.  The shim restores registers/TLB/CP0 and then ERETs.

ORDER MATTERS:
  0. working Status (kernel, KX so 64-bit loads are legal, EXL, interrupts off)
  1. TLB   (Index/EntryHi/EntryLo0/EntryLo1/PageMask/TLBWI x48)
  2. CP0   (skipping Status/EPC/Cause, which are set last)
  3. FP    (FPRs + FCSR)  -- needs CU1 enabled in the working Status
  4. HI/LO
  5. GPRs  -- last, because the shim needs registers to function; k0/k1 are the
     scratch pair and are restored at the very end
  6. EPC = checkpoint pc, Status = checkpoint Status, then ERET (restores PC and
     privilege atomically -- the architectural way to land)
"""
import sys, struct
import ckpt

# CP0 register numbers
C0_INDEX, C0_ENTRYLO0, C0_ENTRYLO1, C0_PAGEMASK = 0, 2, 3, 5
C0_ENTRYHI, C0_STATUS, C0_CAUSE, C0_EPC = 10, 12, 13, 14
# CP0 regs the shim restores directly (32-bit view); Status/Cause/EPC handled last
C0_SIMPLE = [1, 4, 6, 7, 8, 9, 11, 16, 17, 18, 19, 20, 28, 29, 30]
# 64-bit CP0 regs restored via DMTC0
C0_64 = [2, 3, 4, 8, 10, 20, 30]

BLOB_GPR, BLOB_FPR, BLOB_C064 = 0x000, 0x100, 0x200
BLOB_TLB, BLOB_MISC = 0x300, 0x900          # TLB: 48*32 = 0x600 bytes


def emit(c, blob_va):
    o = []
    a = o.append
    a("/* AUTO-GENERATED by gen_shim.py -- do not edit */")
    a("    .set noreorder")
    a("    .set noat")
    a("    .set mips3")
    a("    /* FR=1 view: the checkpoint holds 32 independent 64-bit FPRs, so odd")
    a("     * ldc1 targets must be legal.  Status.FR (bit 26) is set in the working")
    a("     * Status below; without fp=64 the assembler rejects odd $f under FR=0,")
    a("     * which is the same constraint that caused an RI panic on this core. */")
    a("    .set fp=64")
    a("    .globl _shim_start")
    a("_shim_start:")
    a("    /* ---- 0. working Status: kernel, KX/SX/UX, CU1, EXL, IE off ---- */")
    a("    lui   $k1, 0x3400          /* CU1 | KX-ish working set */")
    a("    ori   $k1, $k1, 0x0002     /* EXL */")
    a("    mtc0  $k1, $12")
    a("    nop")
    a("    /* ---- blob base (uncached kseg1 so no TLB dependency) ---- */")
    a("    lui   $k0, 0x%04x" % ((blob_va >> 16) & 0xFFFF))
    a("    ori   $k0, $k0, 0x%04x" % (blob_va & 0xFFFF))

    a("    /* ---- 1. TLB: %d entries ---- */" % ckpt.NTLB)
    for i in range(ckpt.NTLB):
        b = BLOB_TLB + i * 32
        a("    li    $k1, %d" % i)
        a("    mtc0  $k1, $%d" % C0_INDEX)
        a("    ld    $k1, %d($k0)" % (b + 0));  a("    dmtc0 $k1, $%d" % C0_ENTRYHI)
        a("    ld    $k1, %d($k0)" % (b + 8));  a("    dmtc0 $k1, $%d" % C0_ENTRYLO0)
        a("    ld    $k1, %d($k0)" % (b + 16)); a("    dmtc0 $k1, $%d" % C0_ENTRYLO1)
        a("    lw    $k1, %d($k0)" % (b + 24)); a("    mtc0  $k1, $%d" % C0_PAGEMASK)
        a("    nop")
        a("    tlbwi")
        a("    nop")

    a("    /* ---- 2. CP0 (64-bit shadow first, then 32-bit) ---- */")
    for r in C0_64:
        if r in (C0_STATUS, C0_EPC, C0_CAUSE):
            continue
        a("    ld    $k1, %d($k0)" % (BLOB_C064 + r * 8))
        a("    dmtc0 $k1, $%d" % r)
    for r in C0_SIMPLE:
        a("    lw    $k1, %d($k0)" % (BLOB_C064 + r * 8))   # low word of the shadow
        a("    mtc0  $k1, $%d" % r)

    a("    /* ---- 3. FP: FPRs then FCSR ---- */")
    for i in range(32):
        a("    ldc1  $f%d, %d($k0)" % (i, BLOB_FPR + i * 8))
    a("    lw    $k1, %d($k0)" % (BLOB_MISC + 0x20))
    a("    ctc1  $k1, $31")

    a("    /* ---- 4. HI/LO ---- */")
    a("    ld    $k1, %d($k0)" % (BLOB_MISC + 0x00));  a("    mthi  $k1")
    a("    ld    $k1, %d($k0)" % (BLOB_MISC + 0x08));  a("    mtlo  $k1")

    a("    /* ---- 5. GPRs (k0=26, k1=27 last; r0 skipped) ---- */")
    for i in range(1, 32):
        if i in (26, 27):
            continue
        a("    ld    $%d, %d($k0)" % (i, BLOB_GPR + i * 8))

    a("    /* ---- 6. EPC + final Status, then ERET ---- */")
    a("    ld    $k1, %d($k0)" % (BLOB_MISC + 0x10))
    a("    dmtc0 $k1, $%d" % C0_EPC)
    a("    ld    $k1, %d($k0)" % (BLOB_MISC + 0x18))
    # keep EXL set so the remaining kseg0 fetches below still run privileged;
    # ERET clears EXL and lands in the checkpoint's mode.  (A checkpoint taken
    # with EXL already set cannot be expressed this way -- ERET would clear it.) */
    a("    ori   $k1, $k1, 0x0002     /* EXL: stay kernel until ERET */")
    a("    mtc0  $k1, $%d" % C0_STATUS)
    a("    nop")
    a("    /* k1 is clobbered below; k0/k1 come from the blob's own slots */")
    a("    ld    $k1, %d($k0)" % (BLOB_GPR + 27 * 8))
    a("    ld    $k0, %d($k0)" % (BLOB_GPR + 26 * 8))
    a("    eret")
    a("    nop")
    return "\n".join(o)


def blob(c):
    """BIG-endian: the checkpoint FILE is little-endian (written by an x86 host,
    parsed as such in ckpt.py) but the MIPS target reads this blob big-endian.
    Getting this wrong is silent -- the shim runs to completion and ERETs to a
    byte-swapped PC, which shows up as an AdEL on 441b0e88ffffffff instead of
    ffffffff880e1b44."""
    b = bytearray(BLOB_MISC + 0x40)
    for i in range(32):
        struct.pack_into(">q", b, BLOB_GPR + i * 8, c.gpr[i])
        struct.pack_into(">Q", b, BLOB_FPR + i * 8, c.cpr1[i])
        struct.pack_into(">Q", b, BLOB_C064 + i * 8, c.cpr0_64[i])
    for i, t in enumerate(c.tlb):
        off = BLOB_TLB + i * 32
        struct.pack_into(">QQQI", b, off, t["hi"], t["lo0"], t["lo1"], t["mask"])
    struct.pack_into(">q", b, BLOB_MISC + 0x00, c.hi)
    struct.pack_into(">q", b, BLOB_MISC + 0x08, c.lo)
    struct.pack_into(">q", b, BLOB_MISC + 0x10, c.pc)          # -> EPC
    struct.pack_into(">I", b, BLOB_MISC + 0x1C, c.cpr0[c.STATUS])  # low word of the 64b slot
    struct.pack_into(">I", b, BLOB_MISC + 0x24, c.fcr1[4])         # FCSR, ditto
    return bytes(b)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: gen_shim.py <checkpoint> [blob_va]")
    c = ckpt.Checkpoint(sys.argv[1])
    va = int(sys.argv[2], 0) if len(sys.argv) > 2 else 0xA0700000
    sys.stderr.write("[shim] %s\n" % c.summary())
    open("shim.S", "w").write(emit(c, va) + "\n")
    open("shim_blob.bin", "wb").write(blob(c))
    sys.stderr.write("[shim] wrote shim.S (%d lines) + shim_blob.bin (%d bytes) blob_va=%#x\n"
                     % (emit(c, va).count("\n") + 1, len(blob(c)), va))
